export const USER_ROWS_ADD = 'USER_ROWS_ADD';
export const USER_ROWS_CORRECT_NUMBER = 'USER_ROWS_CORRECT_NUMBER';
export const USER_ROWS_SORT_ROW = 'USER_ROWS_SORT_ROW';
export const USER_ROWS_SORT_ROWS = 'USER_ROWS_SORT_ROWS';

export default {
	USER_ROWS_ADD,
	USER_ROWS_CORRECT_NUMBER,
	USER_ROWS_SORT_ROW,
	USER_ROWS_SORT_ROWS
};