export const CORRECT_NUMBER_RECEIVED = 'CORRECT_NUMBER_RECEIVED';
export const CORRECT_NUMBER_WAITING = 'CORRECT_NUMBER_WAITING';
export const CORRECT_NUMBER_ANIMATING = 'CORRECT_NUMBER_ANIMATING';
export const CORRECT_NUMBER_CORRECTING = 'CORRECT_NUMBER_CORRECTING';
export const CORRECT_NUMBER_CORRECTED = 'CORRECT_NUMBER_CORRECTED';
export const CORRECTION_READY_TO_START = 'CORRECTION_READY_TO_START';
export const CORRECTION_STARTING = 'CORRECTION_STARTING';
export const CORRECTION_STARTED = 'CORRECTION_STARTED';

export default {
	CORRECT_NUMBER_RECEIVED,
	CORRECT_NUMBER_WAITING,
	CORRECT_NUMBER_ANIMATING,
	CORRECT_NUMBER_CORRECTING,
	CORRECT_NUMBER_CORRECTED,
	CORRECTION_READY_TO_START,
	CORRECTION_STARTING,
	CORRECTION_STARTED
};
